/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnknownRouteImport } from './routes/unknown'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CamerasIndexRouteImport } from './routes/cameras.index'
import { Route as PeopleNewRouteImport } from './routes/people.new'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as CamerasCameraIdRouteImport } from './routes/cameras.$cameraId'

const UnknownRoute = UnknownRouteImport.update({
  id: '/unknown',
  path: '/unknown',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIndexRoute = CamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleNewRoute = PeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasCameraIdRoute = CamerasCameraIdRouteImport.update({
  id: '/cameras/$cameraId',
  path: '/cameras/$cameraId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/unknown': typeof UnknownRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/cameras/': typeof CamerasIndexRoute
  '/events/': typeof EventsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/unknown': typeof UnknownRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/cameras': typeof CamerasIndexRoute
  '/events': typeof EventsIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/unknown': typeof UnknownRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/cameras/': typeof CamerasIndexRoute
  '/events/': typeof EventsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/settings'
    | '/test'
    | '/unknown'
    | '/cameras/$cameraId'
    | '/events/$eventId'
    | '/people/$personId'
    | '/people/new'
    | '/cameras/'
    | '/events/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/settings'
    | '/test'
    | '/unknown'
    | '/cameras/$cameraId'
    | '/events/$eventId'
    | '/people/$personId'
    | '/people/new'
    | '/cameras'
    | '/events'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/settings'
    | '/test'
    | '/unknown'
    | '/cameras/$cameraId'
    | '/events/$eventId'
    | '/people/$personId'
    | '/people/new'
    | '/cameras/'
    | '/events/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  UnknownRoute: typeof UnknownRoute
  CamerasCameraIdRoute: typeof CamerasCameraIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleNewRoute: typeof PeopleNewRoute
  CamerasIndexRoute: typeof CamerasIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unknown': {
      id: '/unknown'
      path: '/unknown'
      fullPath: '/unknown'
      preLoaderRoute: typeof UnknownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/': {
      id: '/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof CamerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/new': {
      id: '/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof PeopleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$cameraId': {
      id: '/cameras/$cameraId'
      path: '/cameras/$cameraId'
      fullPath: '/cameras/$cameraId'
      preLoaderRoute: typeof CamerasCameraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  UnknownRoute: UnknownRoute,
  CamerasCameraIdRoute: CamerasCameraIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleNewRoute: PeopleNewRoute,
  CamerasIndexRoute: CamerasIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
